MORE GitHub edits
fedKotikeD-org/Bluespace-Station pull request #11
Opened 2023-03-27 17:24 UTC by dopoi16-txt

 **Описание PR**
  
 3ed684c626266ad4d46c1ed1672c5639475aeec7 - переименована папка гитхаба (не знаю получилось ли, проводник шалит)
 9d4bef1f9f31556688fb0b307939da258b960c95 - немного изменен шаблон ПРа так как применяется другой формат текста

  
  
 **Проверки** 
  
 - [X] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [ ] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 
  
 **Изменения** 
  
  
 :cl: 
 - add: GH: добавил READE.ME
 - fix: GH: папка github переименована

2023-03-27 17:29 UTC, fedKotikeD requested changes
Не, все окей. Но 3ed684c626266ad4d46c1ed1672c5639475aeec7 не переименовалось. Подождем до завтра, там попробую откатить

2023-03-28 06:44 UTC, fedKotikeD commented
@dopoi16-txt дайте доступ к вашему форку дабы я мог откатить изменения

2023-03-28 06:47 UTC, dopoi16-txt commented
> @dopoi16-txt дайте доступ к вашему форку дабы я мог откатить изменения

вроде дал

2023-03-28 06:55 UTC, fedKotikeD approved these changes
Чилл

2023-03-28 06:56 UTC, merged