Another GitHub change
fedKotikeD-org/Bluespace-Station pull request #12
Opened 2023-04-08 14:26 UTC by dopoi16-txt

**Описание PR**
  
Продолжаем изменения гитхаба  

 
  
  
 **Проверки** 
  
 - [X] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [X] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 
  
 **Изменения** 
  
  
 :cl: 
 - tweak: GH: Изменен README
 - remove: GH: Убран labeler.yml
 - tweak: GH: файлы перемещены в папку other

2023-04-08 14:27 UTC, fedKotikeD requested changes
Надо вернуть labeler.yml потому что он может заработать

2023-04-10 16:59 UTC, fedKotikeD approved these changes

2023-04-10 16:59 UTC, fedKotikeD commented on README.md
> +Server content - файлы сервера
@dopoi16-txt

2023-04-10 17:00 UTC, dopoi16-txt commented on README.md
> +Server content - файлы сервера
уже сделал

2023-04-10 17:01 UTC, merged