New files update
fedKotikeD-org/Bluespace-Station pull request #19
Opened 2023-04-16 17:36 UTC by dopoi16-txt

**Описание PR**
  
closes #18 

  

 **Проверки** 
  
 - [X] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [X] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
  

 :cl:
-

2023-04-16 17:53 UTC, fedKotikeD requested changes

2023-04-16 17:53 UTC, fedKotikeD commented on Tools/actions_changelogs_since_last_run.py
> +#!/usr/bin/env python3
_Привязано не к файлу, а к комиту_

Необходимо добавить папку Secrets (пустую)

2023-04-18 10:46 UTC, fedKotikeD requested changes
Смотрите предыдущий ревью в дополнение к этому. Также в связи с проблемой с RobustToolbox ставлю тег invalid

2023-04-18 10:46 UTC, fedKotikeD commented on RobustToolbox/.editorconfig
> +﻿root = true
_Привязано не к файлу а к коммиту_

Нужно сделать ссылку как на официальном источнике,а то выглядит не корректно

2023-04-19 10:56 UTC, dopoi16-txt commented on Tools/actions_changelogs_since_last_run.py
> +#!/usr/bin/env python3
Попробовал. Пустую папку не создать. Только с чем-то внутри. Так что не получится

2023-04-19 10:58 UTC, dopoi16-txt commented
Вроде по всем проблемам отписал. Больше ничего исправить не могу

2023-04-19 11:00 UTC, fedKotikeD approved these changes
Тогда все окей

2023-04-19 11:00 UTC, merged