Create new map
fedKotikeD-org/Bluespace-Station pull request #24
Opened 2023-04-20 18:17 UTC by dopoi16-txt

closes #21 
 

 **Описание PR**
  
Создаю новую карту для сервера
**Медиа**
Будут позже
  

 **Проверки** 
  
 - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [X] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
  

 :cl: 
 - add: Добавлена карта Bluepsace

2023-04-20 18:18 UTC, dopoi16-txt commented
По сути я копировал бокс но добавил всякие прикольные фигулины: перевод факсов + варпов, клувень в техах, добавил кнопки сигналов для разных шторок + шторки в операционную. Также планирую обрезать РНД часть с атмосом и подкорректировать (уменьшить) некоторые другие отделы

2023-04-20 18:21 UTC, fedKotikeD commented
> По сути я копировал бокс но добавил всякие прикольные фигулины: перевод факсов + варпов, клувень в техах, добавил кнопки сигналов для разных шторок + шторки в операционную. Также планирую обрезать РНД часть с атмосом и подкорректировать (уменьшить) некоторые другие отделы

Гляну карту

2023-04-21 17:36 UTC, dopoi16-txt commented
Скрины добавлю позже

2023-04-21 17:48 UTC, fedKotikeD requested changes
Переделать моё + сузить карту

2023-04-21 17:48 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
> +  id: BlespaceBox
Blespace?
```suggestion
  id: BluespaceBox
```

2023-04-21 17:48 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
> +        Lawyer: [ 0, 0 ]
Надо бы хотя бы одного...

2023-04-21 17:48 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
> +      mapNameTemplate: '{0} Box Station {1}'
После него добавить свой видоизмененный шаттл дельты

2023-04-21 17:48 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
Также добавить зоотехника

2023-04-21 17:48 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Corvax/Maps/Pools/default.yml
А тут убрать все кроме нашей

2023-04-21 17:54 UTC, dopoi16-txt commented on Server content/Resources/Prototypes/Corvax/Maps/Pools/default.yml
В fix2

2023-04-21 18:21 UTC, dopoi16-txt commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
> +        Lawyer: [ 0, 0 ]
fix2

2023-04-21 18:21 UTC, dopoi16-txt commented on Server content/Resources/Prototypes/Corvax/Maps/bluespaceBox.yml
> +      mapNameTemplate: '{0} Box Station {1}'
fix3

2023-04-22 09:58 UTC, fedKotikeD requested changes
Пока что проводите тест и не забудьте все-таки привязать шаттл к станции, а то вы шаттл сделали но не привязали

2023-04-22 12:12 UTC, fedKotikeD approved these changes
Вроде бы все супер. Тогда добавляю в merge queue

2023-04-22 13:21 UTC, merged