Add new stamps
fedKotikeD-org/Bluespace-Station pull request #25
Opened 2023-04-21 14:25 UTC by dopoi16-txt

**Описание PR**
  
Добавлены печать админа и "НЕ ПО ФОРМЕ"
 **Медиа** 
  
_Будет позже_

 **Проверки** 
  
 - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [ ] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
  

 :cl: 
 - add: Добавлена печать админов (богов)
 - add: Добавлена печать "НЕ ПО ФОРМЕ", для тех, кто не умеет писать
 - tweak: В шкаф главе персонала добавлена печать "НЕ ПО ФОРМЕ"

2023-04-21 14:26 UTC, dopoi16-txt commented
Не по форме сейчас добавлю

2023-04-21 14:34 UTC, dopoi16-txt commented
Осталось только проверить на локалке

2023-04-21 14:35 UTC, fedKotikeD requested changes
Хорошо, жду

2023-04-24 17:10 UTC, dopoi16-txt commented
У меня тест не проводится поэтому добавлю текстурки и думаю можно одобрять

2023-04-24 18:21 UTC, dopoi16-txt commented
> У меня тест не проводится поэтому добавлю текстурки и думаю можно одобрять

А, еще ведь к ГП добавить печать

2023-04-24 18:29 UTC, dopoi16-txt commented
Ай эм рэди

2023-04-24 18:31 UTC, fedKotikeD commented
Пока что не могу добавить в очередь. Как смогу - появится значок

2023-04-25 05:13 UTC, fedKotikeD approved these changes

2023-04-25 10:40 UTC, merged