Upgrade builder
fedKotikeD-org/Bluespace-Station pull request #36
Opened 2023-04-26 19:03 UTC by dopoi16-txt

closes #35 
 

 **Описание PR**
  
Пока что черновик чтобы потом доделать

 
  

 **Проверки** 
  
 - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [ ] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
  

 :cl: 
 - tweak: НТ изменило свое отношение к строителю и решило предоставить ему пояс старшего инженера

2023-04-27 06:18 UTC, dopoi16-txt commented
My to-do list:
- [ ] Шкаф (код)
- [ ] Шкаф (спрайт)
- [ ] Шкаф (локализация)
- [ ] РСУ (код)
- [ ] Скафандр (код)
- [ ] Скафандр (спрайт)
- [ ] Скафандр (локализация)

2023-04-28 17:09 UTC, fedKotikeD requested changes
Нету иконки строителя

2023-04-28 18:35 UTC, dopoi16-txt commented
> Нету иконки строителя

Сделаю

2023-04-28 19:27 UTC, fedKotikeD requested changes
И ещё мету к спрайтам добавить. 
Так и быть, закрою глаза на скафандр если сделаете иконку

2023-04-28 19:27 UTC, fedKotikeD commented on Server content/Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/lockers/engineer.ftl
> +    .desc = { ent-LockerEngineer.desc }
```suggestion
    .desc = { ent-LockerBuilder.desc }
```

2023-04-28 19:27 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
> +      - id: NitrogenTankFilled
```suggestion
 
```

2023-04-29 08:22 UTC, fedKotikeD approved these changes

2023-04-29 08:22 UTC, fedKotikeD commented
Чуть позже проверю на локальном сервере изменения

2023-04-29 11:10 UTC, merged