Blue shield
fedKotikeD-org/Bluespace-Station pull request #43
Opened 2023-04-30 11:17 UTC by dopoi16-txt

**Описание PR**
  
Добавляет роль офицера синего щита

 **Медиа** 
  
Чуть позже добавлю

 **Проверки** 
  
 - [X] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [X] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
  

 :cl: dopoi16-txt
 - add: Добавлен офицер синего щита

2023-04-30 11:35 UTC, fedKotikeD requested changes
Конфликты + я еще не проверил

2023-04-30 11:40 UTC, fedKotikeD reviewed
Проверяю файлы...

2023-04-30 18:34 UTC, fedKotikeD requested changes

2023-04-30 18:34 UTC, fedKotikeD commented on Server content/Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
> +    .desc =Костюм, достаточно прочный, чтобы выдержать сотни пуль, защищая при этом подопечного.
```suggestion
    .desc = Костюм, достаточно прочный, чтобы выдержать сотни пуль, защищая при этом подопечного.
```

2023-04-30 18:34 UTC, fedKotikeD commented on Server content/Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = На удивление ничем не отличается от вашего КПК.
Поменять на остроумное описание

2023-04-30 18:34 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Slash: 0.9
Че такая маленькая защита?

2023-04-30 18:34 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Roles/Jobs/Command/blue_shield.yml
> +      time: 324000 # Corvax-RoleTime
```suggestion
      time: 648000 # Corvax-RoleTime
```
Это ОЧЕНЬ важная должность

2023-04-30 18:34 UTC, fedKotikeD commented on Server content/Resources/Prototypes/Roles/Jobs/Command/blue_shield.yml
> +  icon: "Blueshield" #sprite
Нету такой

2023-04-30 18:38 UTC, fedKotikeD approved these changes
Все проблемки пофиксил сам, но иконку нужно сделать

2023-04-30 18:41 UTC, fedKotikeD requested changes
А стоп, спавнер на карту не добавил

2023-05-01 13:34 UTC, dopoi16-txt commented
> А стоп, спавнер на карту не добавил

У меня баг и не получается. Пока что придется мерджить так

2023-05-01 13:50 UTC, fedKotikeD requested changes
Какое мерджить? Иконка и спавнер будут готовы - будет MERGED. Пока не готово, сделаб драфтом

2023-05-01 13:51 UTC, fedKotikeD commented
Переоткрою позже. Либо делайте новый ПР, но уже готовый

2023-05-02 17:10 UTC, fedKotikeD approved these changes
Почему-то при билде у меня слетают текстуры печатей, но думаю это поправится. Сейчас сделаю иконку ему

2023-05-02 17:20 UTC, OMGazk88 approved these changes
[textures review] Ну текстурки плюс минус сделаны неплохо. Одобряю

2023-05-02 17:20 UTC, merged